### ISSUE TITLE
Looking Forward the Code

### ISSUE THREAD

**Issue by ligaoqi2** [ViTAE-Transformer/ViTPose#1]
How long until the code is released？
Thanks

**Comment by rebotnix** [comment]
Great project. Would like to transport it to NVIDIA new Edge Orin Device.

**Comment by ahmadmustafaanis** [comment]
Waiting

**Comment by Annbless** [comment]
Hi,

Thank you for your interest! We have uploaded logs for the ViT-Base, ViT-Large and ViT-Huge models. The code and pre-trained models are in preparation and we are working on exploring more potential of the simple visual transformers for pose estimation. We think the code and models will be released before 1th July.

**Comment by NielsRogge** [comment]
Subscribing to this thread as I might add the model to HuggingFace Transformers ;)

**Comment by satpalsr** [comment]
@NielsRogge Can I join you in doing so?

**Comment by Annbless** [comment]
Hi,

The code and pre-trained models for ViTPose have been released! 
Please try and enjoy~

If there are any questions, please not hesitate to contact~ 😊

**Comment by ahmadmustafaanis** [comment]
Trying it right now.

**Comment by ligaoqi2** [comment]
Thank you so much～
Surprisingly open source in advance～
