### ISSUE TITLE
The checkpoints of "whole body" are wrong.

### ISSUE THREAD

**Issue by mornfairy** [ViTAE-Transformer/ViTPose#112]
The checkpoints of wholebody are wrong, the inference result is very low confidence, about 0.0000-0.00001. When I visualize the result, the key points are disordered. Can you provide the correct checkpoints of wholebody?

**Comment by mornfairy** [comment]
<img width="454" alt="Snipaste_2023-08-01_15-50-35" src="https://github.com/ViTAE-Transformer/ViTPose/assets/42601403/bef4ec55-bb1f-4510-898d-3e90e49c0763">

**Comment by mornfairy** [comment]
all the wholebody models



---Original---
From: "Jinheng ***@***.***&gt;
Date: Tue, Aug 29, 2023 23:21 PM
To: ***@***.***&gt;;
Cc: "Yongchang ***@***.******@***.***&gt;;
Subject: Re: [ViTAE-Transformer/ViTPose] The checkpoints of "whole body" arewrong. (Issue #112)




 
Hi, I got the size mismatch error. Which checkpoint do you use? @mornfairy

**Comment by GiangMax** [comment]
Hi, were you able to find out more about this?

@Annbless @seaman1900 @AK391 Do the wholebody models work for you?

**Comment by developer0hye** [comment]
@mornfairy @Annbless @seaman1900 @AK391 

1. Split weights with [this modification](https://github.com/ViTAE-Transformer/ViTPose/pull/117/files)

2. Load a model with splitted weights

You can inference an image with the above steps.

![sample_ViTPose+_huge_coco_wholebody](https://github.com/ViTAE-Transformer/ViTPose/assets/35001605/2ae94c21-d49a-4ec8-bb63-dfd8434e79c4)

You can easily predict an image with https://github.com/developer0hye/onepose.
