### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by MikuuGithub** [ViTAE-Transformer/ViTPose#13]
Can you explain what nMS_THr and OKs_THr mean and what they do?
Thank you very much!
![nms_thr=1 0](https://user-images.githubusercontent.com/24295745/173743839-8bda2579-b885-4404-a07a-3e1831e9a940.png)

**Comment by Annbless** [comment]
This is the default post-processing hyper-parameters to reduce duplicate predictions.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close the issue temporarily. If you have any further questions, please feel free to re-open it.
