### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by EEWenbinWu** [ViTAE-Transformer/ViTPose#16]
can you provide us the pretrained MAE or VITAE?

**Comment by Annbless** [comment]
Hi,

the pretrained models of MAE can be downloaded from MAE official repo, e.g., [https://github.com/facebookresearch/mae](https://github.com/facebookresearch/mae).

**Comment by mariolew** [comment]
How about the pretrained model used in the paper, i.e., pretrained for 1600 epochs.

**Comment by Annbless** [comment]
The models pretrained by MAE are trained for 1600 epochs.  You can directly use these pretrained models to reproduce the results in the paper.
