### ISSUE TITLE
About multitask log

### ISSUE THREAD

**Issue by EEWenbinWu** [ViTAE-Transformer/ViTPose#17]
Thx for the great work! It helps me l lot in my own study. Could you please release the training log of the multitask training? The .log file may better than .json. Thx again.

**Comment by Annbless** [comment]
Hi, the training log and code of the multiple task training have been uploaded.
I will close this issue temporarily. If you have some further questions, please feel free to re-open it.

**Comment by EEWenbinWu** [comment]
sorry, I can't find anything about "TopDownMultiHeadMOE"
