### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by cheesezoella** [ViTAE-Transformer/ViTPose#19]
Hi, can anyone summarize the installation setup and the quick start process (for instance using the demo and running the inference). The instructions mentioned in the README.md is confusing for beginners. Thank you !!!

**Comment by ExponentialML** [comment]
It's kind of hidden, but check [here](https://github.com/ViTAE-Transformer/ViTPose/tree/main/demo). Click the task you want, and the example codes are there.

**Comment by cheesezoella** [comment]
Hi, thank you!! May i know which commands/file to run to get the benchmark like fps or inference time?? :)
