### ISSUE TITLE
Top-down or bottom-up?

### ISSUE THREAD

**Issue by louislva** [ViTAE-Transformer/ViTPose#2]
Hey! Was reading the paper, impressive stuff.

I was uncertain about what you actually predicted however. Do you do first crop the humans, and then do keypoint estimation (top-down I guess)? Or do you predict all humans at once (bottom-up), and then predict a part-affinity map (or the like) along with the keypoints? 

If it's the latter, what exactly does the model output?

Thank you in advance 🙏

**Comment by RogerZhangzz** [comment]
Hi,
Thank you for your interest!
We use top-down prediction in ViTPose. The input is cropped images of humans and the output is the heatmap of the key points.

**Comment by NeelayS** [comment]
> Hi, Thank you for your interest! We use top-down prediction in ViTPose. The input is cropped images of humans and the output is the heatmap of the key points.

Do you also provide code for going from the heatmap to the keypoint locations?
