### ISSUE TITLE
What is the pretrain model of MAE huge?

### ISSUE THREAD

**Issue by zengwang430521** [ViTAE-Transformer/ViTPose#28]
I found that in [MAE project](https://github.com/facebookresearch/mae/blob/efb2a8062c206524e35e47d04501ed4f544c0ae8/models_mae.py#L239), the huge model has a patch_size = 14. But in the [config](https://github.com/ViTAE-Transformer/ViTPose/blob/a43e06acd301df1a336ae902747442ebefbfb840/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_huge_coco_256x192.py#L49), the patch size is set to 16. How do you load the MAE pretrained weights?

**Comment by DongHappyyy** [comment]
Hello, I have the same question with you. So, could you tell me how to load the MAE pretrained weights?
