### ISSUE TITLE
Video demo with VitPose Base

### ISSUE THREAD

**Issue by gsrujana** [ViTAE-Transformer/ViTPose#31]
Hello, how to run video demo with Vit.Are the demo scripts using any Vit pose models? As it says in demo page - Using mmdet for human bounding box detection. We provide a demo script to run mmdet for human detection, and mmpose for pose estimation. How to use VItPose for videopose estimation?

**Comment by gsrujana** [comment]
Ideally, I want to be able to choose the weight files for inference on videos. Thanks

**Comment by ajktym94** [comment]
Hey! I think you have to use this config file while running it:
`configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_base_coco_256x192.py`

**Comment by ajktym94** [comment]
@gsrujana Can you help me with installing the libraries properly? I have been trying to fix this for a long time without any success. Seems like dependency issues and I see multiple ways for installation in the documentation.

**Comment by gsrujana** [comment]
> Hey! I think you have to use this config file while running it: `configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_base_coco_256x192.py`

That helped. Thanks! Do you know whether this can be run on cpu?

**Comment by gsrujana** [comment]
> @gsrujana Can you help me with installing the libraries properly? I have been trying to fix this for a long time without any success. Seems like dependency issues and I see multiple ways for installation in the documentation.

Sure. I replied on your issue.

**Comment by gsrujana** [comment]
I was wondering how to optimize this. In my case, I only have single person in frame. Can I use this directly without bounding box detector?

**Comment by ajktym94** [comment]
> > Hey! I think you have to use this config file while running it: `configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_base_coco_256x192.py`
> 
> That helped. Thanks! Do you know whether this can be run on cpu?

I hope yes.
