### ISSUE TITLE
How to edit number of transformer blocks?

### ISSUE THREAD

**Issue by gsrujana** [ViTAE-Transformer/ViTPose#36]
Hi, Can you please point to part in config or scripts to change number of transformer blocks in the network for training?
Thanks

**Comment by Annbless** [comment]
Please simply change the depth attribute in the [config files](https://github.com/ViTAE-Transformer/ViTPose/blob/main/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_base_coco_256x192.py#L51).
