### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by levan92** [ViTAE-Transformer/ViTPose#4]
Thank you for the nice work! May I know if you all have done any analysis and comparison for the model's inference speed?

**Comment by Annbless** [comment]
Hi, thanks for your interest. We will update the detailed comparisons in the paper. 
Roughly speaking, in our experiment environments, the ViTPose-b model runs a little faster than HRNet-w32, i.e. over 900fps on a single A100GPU without the flip test.

**Comment by levan92** [comment]
Alright, will look out for your updated paper 😄  Thank you!

**Comment by levan92** [comment]
Sorry @Annbless just to clarify, you were saying the ViTPose-b model is over 900FPS on A100? Or is it a typo, 90FPS instead?

**Comment by Annbless** [comment]
900 fps, with 64 batch size, 256x192 input resolutions, and without flip test, We just iteratively feed the inputs into the model for calculation after several warmup iterations. The average speed is calculated then. We have updated the results in the paper, please refer to [arxiv](https://arxiv.org/abs/2204.12484).

The code for the speed test is rather simple as follows, 
![image](https://user-images.githubusercontent.com/32097042/170238854-82f0226b-bbc0-43b6-925a-cd0103f9d382.png)

**Comment by levan92** [comment]
I see! That make sense 😄  Thanks for sharing the detailed answer!

**Comment by cheesezoella** [comment]
Hi, may i know i can i run the inference speed code? I could not seem to find it under the VitPose file? Thank you!!
