### ISSUE TITLE
model mismatch

### ISSUE THREAD

**Issue by XiaodongGuan** [ViTAE-Transformer/ViTPose#41]
Hi, I encountered a mismatch issue when training ViTbase from the pretrained MAE.
**'The model and loaded state dict do not match exactly
unexpected key in source state_dict: cls_token, norm.weight, norm.bias
missing keys in source state_dict: last_norm.weight, last_norm.bias'**
And
**'fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
'**
But the training was not stopped. What actions should I take other than simply loading from the pretrained MAE?

**Comment by XiaodongGuan** [comment]
I loaded the model by: --cfg-options model.pretrained, using the ViTPose_base_coco_256x192 config file, and no more dedicated change.
Your answer would be deeply appreciated. Thank you.

**Comment by Annbless** [comment]
It is normal to have these warnings of mismatched keys as we do not use the cls token in the backbone model.

It is wired for the 2nd problem. It seems to be a git problem. Would you provide more details? For example, how do you install this repo?

**Comment by XiaodongGuan** [comment]
Hi, thanks for the reply. I downloaded the repo and install form the repo's root directory, following the instructions in install.md.  I used docker 21.6 NGC so I skipped the ' prepare environment' section.

**Comment by Annbless** [comment]
It seems it is more related to the git configuration and does not affect the training. Please just ignore it.
I will close this issue temporarily. If you have any more questions, please feel free to re-open it.
