### ISSUE TITLE
config.py and weight file to integrate with mmpose framework

### ISSUE THREAD

**Issue by muhammetp** [ViTAE-Transformer/ViTPose#43]
Hi
could elaborate on where the corresponding config and weight files for the integration with mmpose framework

**Comment by Annbless** [comment]
Hi,

Thanks for your interest. We have opened a PR in the mmpose framework and will continually work on the integration work.

I will close this issue temporarily. If you have some further questions, please feel free to re-open it.

**Comment by muhammetp** [comment]
Thank you yufei, good luck with your job
________________________________
