### ISSUE TITLE
Can you share the models on GoogleDrive or BaiduDrive?

### ISSUE THREAD

**Issue by SSongWang** [ViTAE-Transformer/ViTPose#49]
Thanks for your excellent work. I cannot get access to Onedrive. Is there any possible for you to share the trained models on  GoogleDrive or BaiduDrive?

**Comment by Annbless** [comment]
Which model do you need? I can upload it on BaiduDrive/GoogleDrive temporarily and upload all models later since it is too large to upload all models to GoogleDrive/BaiduDrive now...

**Comment by SSongWang** [comment]
Thanks very much. I would like the ViTPose-B model trained on MS COCO dataset. Thanks again.

**Comment by Annbless** [comment]
Hi, the checkpoint for vitpose-b with the classic decoder is available at
link https://pan.baidu.com/s/1INEwBdM9aTbTb_01hmtasg?pwd=g8cr
code g8cr

**Comment by SSongWang** [comment]
Thanks so much!!!

**Comment by MrRabbit2MissCat** [comment]
When can all models be uploaded? Looking forward to it, Thanks very much.
