### ISSUE TITLE
About model size

### ISSUE THREAD

**Issue by glamourzc** [ViTAE-Transformer/ViTPose#50]
Hi，I used the pre-trained model you provided for fine-tuning. Performance and speed is competitive.But the size of the model is about three times larger than you.For example, the size of my vitpose-b is 1.xGB, but yours is 343MB. How can i get a same size model?

**Comment by Annbless** [comment]
Thanks for your interest. I think the size you talk about is the size of the checkpoint, right? The default checkpoint saved contains not only the model's weights but also the optimizer's state. Maybe this is the reason for the larger size of the saved checkpoint.

**Comment by glamourzc** [comment]
> 

Yaeh. My onnx model and trt-fp32 model are the same size as the pth you provided.Thx.

**Comment by SonNguyen2510** [comment]
@glamourzc hi, could you provide the onnx model. I try to convert the vitae-pose B* model but somehow it doesn't work

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.
