### ISSUE TITLE
About the object detection method

### ISSUE THREAD

**Issue by DiwasLamsal** [ViTAE-Transformer/ViTPose#51]
Hi, can you please mention which object detector you used? I could not find it mentioned anywhere.

**Comment by Annbless** [comment]
For the test on the COCO val set, we simply use the detection results provided in simplebaseline.

**Comment by haddagart** [comment]
Where can I find the detection results json file. I am running a test and this file for example is not found: COCO_val2017_detections_AP_H_56_person.json
