### ISSUE TITLE
Onnx version of the model

### ISSUE THREAD

**Issue by SonNguyen2510** [ViTAE-Transformer/ViTPose#53]
Hi, thank you author for the great work.

I really impress with your work. By any chance could you realese the onnx version of Vitpose model?
I tried to run the vitpose B* but failed many times

**Comment by seaman1900** [comment]
you can try following command:
1. download the weight and put it to the pretrained directory;
2. i use this to export the onnx model successfully: python tools/deployment/pytorch2onnx.py configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_base_coco_256x192.py pretrained/vitpose-b-multi-coco.pth
