### ISSUE TITLE
How do you test the fps reported in paper?

### ISSUE THREAD

**Issue by DongHappyyy** [ViTAE-Transformer/ViTPose#54]
Hello, the author. I learn a lot from your work. Thank you for sharing. I have a question to ask, how do you test the fps reported in your paper? I test on your code and the vitpose-b checkpoint, only 184fps, which is far from your 944fps. So I want to ask you how to test your fps.
`
if return_loss:
    return self.forward_train(img, target, target_weight, img_metas, **kwargs)

import time
total_time = 0
total_sample = 0

sta = time.time()
test_results = self.forward_test(img, img_metas, return_heatmap=return_heatmap, **kwargs)
consume = time.time() - sta

total_time += consume
total_sample += img.shape[0]

print(f"batch_size: {img.shape[0]}")
print(f"time comsume: {consume}")
print(f"average comsume: {total_time / total_sample:.5f}")
print(f"average fps: {total_sample / total_time:.5f}")

return test_results
`

**Comment by Annbless** [comment]
Hi, 

Thanks for your interest. Please refer to [the speed test file](https://github.com/ViTAE-Transformer/ViTPose/blob/main/tools/analysis/speed_test.py).

**Comment by DongHappyyy** [comment]
^v^~
