### ISSUE TITLE
Multi-dataset training config

### ISSUE THREAD

**Issue by haoyayuzzzz** [ViTAE-Transformer/ViTPose#56]
Hello, the author. I learn a lot from your work. Thank you for sharing. I want to know when can the config of multi-dataset training  and relative code be updated?

**Comment by nini0919** [comment]
Hello author, when will your multi-task training code be open source?I really look forward to hearing from you!!

**Comment by Annbless** [comment]
Hi, the training code and the corresponding logs have been uploaded. I will close this issue since it seems the issue is fixed. If you have some further questions, please feel free to re-open it.
