### ISSUE TITLE
Requesting dataset -ratio information on training parameters for reproducing ViTPose-B results

### ISSUE THREAD

**Issue by TzRain** [ViTAE-Transformer/ViTPose#58]
It would be great if you could provide me with the ratio of each dataset and the number of iterations per epoch you used when training ViTPose-B with COCO+AIC+MPII. I have been trying to reproduce the results, but have only been able to achieve an average precision of 76.2, while I am expecting to see a result of 77.1. Any information you can provide would be greatly appreciated. Thank you for your time.

**Comment by Annbless** [comment]
We have uploaded the multiple datasets code for training. Please refer to it.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.
