### ISSUE TITLE
Vitpose+ - coco wholebody

### ISSUE THREAD

**Issue by ferhatsb** [ViTAE-Transformer/ViTPose#59]
Hey, i want to congratulate you for the new paper. Do you plan to add Vitpose+'s code and models  ?

**Comment by Annbless** [comment]
Hi,

Thanks for your attention. The code for the model definition of ViTPose+ is updated. The pre-trained models, as well as the weights for the small-size models, will be uploaded soon.

**Comment by ferhatsb** [comment]
> Hi,
> 
> Thanks for your attention. The code for the model definition of ViTPose+ is updated. The pre-trained models, as well as the weights for the small-size models, will be uploaded soon.

Perfect, thanks a lot!

**Comment by ferhatsb** [comment]
Hi @Annbless happy new year! Any update on the weights ? Asking for a friend :smile:
