### ISSUE TITLE
about backbone model

### ISSUE THREAD

**Issue by hotelbread** [ViTAE-Transformer/ViTPose#61]
Hi!!! I appreciate your research! thanks!
But I have a question. As a beginner, how can I train my own dataset? 
I could find a train code, tools/train.py.
Whether I need a backbone model about higher-HRNet. (bottom-up method) 
In the config file, there is written already using 

backbone=dict(type='HRNet')

So I think I got a warning message from this reason about 

"mmpose - WARNING - The model and loaded state dict do not match exactly"
"unexpected key in source state_dict: ~~~~"

If I don't need a backbone model(higher-HRNet), can you tell me how could I fix it up???

Thanks!!! 
seotae89@gmail.com

**Comment by Annbless** [comment]
Please just set the pre-trained entry to be None.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.
