### ISSUE TITLE
Compatibility with mmcv-full==1.7.0

### ISSUE THREAD

**Issue by MaxTeselkin** [ViTAE-Transformer/ViTPose#62]
Hi, thanks for great neural network architecture! Can you please make ViTPose compatible with latest versions mmcv-full? Right now ViTPose supports mmcv-full <=1.5.0, this version of mmcv is quite old and causes a lot of difficulties during containerization. I will be really grateful if you can make ViTPose compatible with new versions of mmcv-full.

UPD: It looks like you simply forgot to update https://github.com/ViTAE-Transformer/ViTPose/blob/main/mmpose/__init__.py
I installed ViTPose in editable mode, changed version check to make it compatible with latest mmcv vesrions, tested my neural network and it worked fine. Please, set mmcv_maximum_version to 1.7.1 in __init__.py

**Comment by Annbless** [comment]
Thanks for your advice! We will update the init file soon.
