### ISSUE TITLE
inference in wild images

### ISSUE THREAD

**Issue by EveningLin** [ViTAE-Transformer/ViTPose#63]
great work! i wonder Whether vitpose can also perform well in field pictures?and could you please show some demo

**Comment by Annbless** [comment]
Hi,

Thanks for your interest. There is a demo of the ViTPose models on the hugging face, and it is free to upload and test the performance on wild images.

Please use the [link](https://github.com/ViTAE-Transformer/ViTPose/blob/74253ac4d468ae8110cbed860ca059e0cc334e52/tools/model_split.py#L45) for more information.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.

**Comment by nikhilchh** [comment]
Currently there is runtime error on VITPOSE image demo on huggingface. 
![image](https://github.com/ViTAE-Transformer/ViTPose/assets/26286970/c4c73342-dbb2-4716-a613-ffd54345779f)
