### ISSUE TITLE
the weight of vitpose+_basth.pth maybe wrong

### ISSUE THREAD

**Issue by seaman1900** [ViTAE-Transformer/ViTPose#64]
I download the weight of coco-wholebody, however, when i use the weight to deploy my model, it reports that:
    load checkpoint from local path: vitpose+_base.pth
    The model and loaded state dict do not match exactly
    size mismatch for keypoint_head.final_layer.bias: copying a param with shape torch.Size([17]) from checkpoint, the shape in current 
    model is torch.Size([133]).

**Comment by ferhatsb** [comment]
Think wholebody models are broken. Not sure but feels like model names are same for all options of wholebody+ so probably they override each other...

**Comment by Annbless** [comment]
For the vitpose+ variants, please first use the command

```python
python tools/model_split.py --source <Pretrained PATH>
```

to extract the weights used for different datasets. The details for the extraction can be found in [Line 45](https://github.com/ViTAE-Transformer/ViTPose/blob/74253ac4d468ae8110cbed860ca059e0cc334e52/tools/model_split.py#L45) in the repo.

**Comment by ferhatsb** [comment]
Hi @Annbless thanks for response. There is a typo at line 43- `args.targetPath`, should be `args.target`.

This did the trick, however I still get the warnings though.

Model seems less accurate then coco, is it expected?

**Comment by Annbless** [comment]
Would you mind making the issue more clear? For example, which model and which dataset is used for testing? So, I can figure out the reason for that.

**Comment by seaman1900** [comment]
> Would you mind making the issue more clear? For example, which model and which dataset is used for testing? So, I can figure out the reason for that.
first, thanks for your great work and reply, I download the weight from here: for ViTPose+-B model [https://1drv.ms/u/s!AimBgYV7JjTlgcckRZk1bIAuRa_E1w?e=ylDB2G](url)
and run the pytorch2onnx.py [https://github.com/ViTAE-Transformer/ViTPose/blob/main/tools/deployment/pytorch2onnx.py](url) script, however the error occurs agian :"The model and loaded state dict do not match exactly"

**Comment by seaman1900** [comment]
> For the vitpose+ variants, please first use the command
> 
> ```python
> python tools/model_split.py --source <Pretrained PATH>
> ```
> 
> to extract the weights used for different datasets. The details for the extraction can be found in [Line 45](https://github.com/ViTAE-Transformer/ViTPose/blob/74253ac4d468ae8110cbed860ca059e0cc334e52/tools/model_split.py#L45) in the repo.

I thought this may be the correct answer for my 'bug', apologize for my carelessness ！

**Comment by ferhatsb** [comment]
> Would you mind making the issue more clear? For example, which model and which dataset is used for testing? So, I can figure out the reason for that.
@Annbless I'm using ViTPose+-H Wholebody model with config ViTPose_huge_wholebody_256x192.py but using a custom dataset. I simply compare confidence levels at same images, seeing minor differences. I will post this as another issue since model separation works with warnings. Thanks again.

**Comment by Nuwan1654** [comment]
I am getting the same issue for [vitPose+_small](https://github.com/ViTAE-Transformer/ViTPose/blob/main/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vitPose%2B_small_coco%2Baic%2Bmpii%2Bap10k%2Bapt36k%2Bwholebody_256x192_udp.py)

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.

**Comment by dinushazoomi** [comment]
@Annbless 

any idea on this,

> I am getting the same issue for [vitPose+_small](https://github.com/ViTAE-Transformer/ViTPose/blob/main/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vitPose%2B_small_coco%2Baic%2Bmpii%2Bap10k%2Bapt36k%2Bwholebody_256x192_udp.py)
> 
> However when I used the config file for [small ](https://github.com/ViTAE-Transformer/ViTPose/blob/74253ac4d468ae8110cbed860ca059e0cc334e52/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/ViTPose_small_coco_256x192.py) model, error went away,
> 
> is it ok to use that different config with the + model?

**Comment by Annbless** [comment]
Please always use the ```tools/model_split.py``` file to extract the corresponding weights and then use the extracted models to make the inference. Otherwise, there may exist missing keys in the backbone model as we use a task-specific FFN layers in the backbone model.

**Comment by Nuwan1654** [comment]
@Annbless After converting the `vitpose+_small.pth` from the MS COCO pre-trained weights, using the `tools/model_split.py` there were several Pytorch weights generated, then I used `coco.pth` and try to convert it to ONNX using `tools/deployment/pytorch2onnx.py` file, and then got the error mentioned in #73.

Are the above steps I took correct, to convert `vitpose+_small.pth` to ONNX format? 

my requirement is I need to run this on the jetson AGX Orin, Currently, I am running the dispose-base model, but I need to test the vitpose+_small model as well, due to its higher FPS shown in the plot.

**Comment by MaxTeselkin** [comment]
@Annbless Unfortunately even after running model_split.py I am still getting size mismatch warnings for vitpose+_small.pth (I tried both for coco anf for ap10k), this size mismatch causes inadequate predictions. When I run model_split.py, it divides vitpose+_small.pth into several .pth files, I am trying to use corresponding file for my needs (for example coco.pth), but it still gives size mismatch warnings and predictions look incorrect.

**Comment by Annbless** [comment]
> @Annbless Unfortunately even after running model_split.py I am still getting size mismatch warnings for vitpose+_small.pth (I tried both for coco anf for ap10k), this size mismatch causes inadequate predictions. When I run model_split.py, it divides vitpose+_small.pth into several .pth files, I am trying to use corresponding file for my needs (for example coco.pth), but it still gives size mismatch warnings and predictions look incorrect.

It is rather weird. I just retried the model following the instructions in the Readme file by first using model split and then conducting the predictions using the corresponding config file. The result of ViTPose+_small on the MS COCO dataset is 75.8 AP. The log is attached for reference. 
[small_prediction.log](https://github.com/ViTAE-Transformer/ViTPose/files/10751877/small_prediction.log)

**Comment by Annbless** [comment]
> @Annbless After converting the `vitpose+_small.pth` from the MS COCO pre-trained weights, using the `tools/model_split.py` there were several Pytorch weights generated, then I used `coco.pth` and try to convert it to ONNX using `tools/deployment/pytorch2onnx.py` file, and then got the error mentioned in #73.
> 
> Are the above steps I took correct, to convert `vitpose+_small.pth` to ONNX format?
> 
> my requirement is I need to run this on the jetson AGX Orin, Currently, I am running the dispose-base model, but I need to test the vitpose+_small model as well, due to its higher FPS shown in the plot.

Sorry that we have not tried to convert the models to onnx. According to the experience, it may be related to the onnx version and need to specify the shape of some tensors in the backbone file.

**Comment by MaxTeselkin** [comment]
@Annbless Hi, thanks for the answer! I am trying to perform animal pose estimation using this [config](https://github.com/ViTAE-Transformer/ViTPose/blob/main/configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/ap10k/ViTPose_small_ap10k_256x192.py) and this [checkpoint](https://1drv.ms/u/s!AimBgYV7JjTlgccrwORr61gT9E4n8g?e=kz9sz5).
I ran model_split.py and got ap10k.pth file, which I used as weights.

Here is how I initialize my model:
```
# define model config and checkpoint
pose_config = os.path.join(self.location, "pose_config.py")
pose_checkpoint = os.path.join(self.location, "ap10k.pth")
# initialize pose estimator
self.pose_model = init_pose_model(pose_config, pose_checkpoint, device=device)
```
Here is how I make prediction:
```
pose_results, returned_outputs = inference_top_down_pose_model(
            self.pose_model,
            image_path,
            bboxes,
            format="xyxy",
            dataset=self.pose_model.cfg.data.test.type,
        )
```
It causes no errors, only size mismatch warning (you also have this warning in log file that you sent me), but prediction looks inadequate. You can see result on the image below:

![cows_prediction](https://user-images.githubusercontent.com/91027877/219368794-20a3bc15-90ff-4ec7-a8b5-20f00b8509c0.jpg)

What am I doing wrong? I have been using your ViTPose classic models for a long time exactly the same way and predictions looked wonderful (for human pose estimation). Now I am trying to use ViTPose+ for animal pose estimation and predictions look weird :(

**Comment by MaxTeselkin** [comment]
@Annbless I am sorry, it was my fault, vitpose+_small.pth model works correctly. Thanks for another wonderful architecture!

**Comment by seaman1900** [comment]
hi, guys! I modify the `model_split.py` file to extract the model which can be directly used by the `top_down_img_demo.py` file in the `demo` directory
``` shell
python model_split.py --source [pre-trainde model] --target [target directory]
```
then
``` shell
python demo/top_down_img_demo.py \
configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/ViTPose_base_wholebody_256x192.py \
target/wholebody.pth  \
--img-root tests/data/coco/ \
--json-file tests/data/coco/test_coco.json \
--out-img-root vis_results
```
here is my pull requests &#8595;
https://github.com/ViTAE-Transformer/ViTPose/pull/79#issue-1599537981

**Comment by syguan96** [comment]
Hi, there still are some unexpected keys. Whether I can ignore this warning?

Info:
unexpected key in source state_dict: backbone.blocks.0.mlp.experts.0.weight, backbone.blocks.0.mlp.experts.0.bias, backbone.blocks.0.mlp.experts.1.weight, backbone.blocks.0.mlp.experts.1.bias, backbone.blocks.0.mlp.experts.2.weight, backbone.blocks.0.mlp.experts.2.bias, backbone.blocks.0.mlp.experts.3.weight, backbone.blocks.0.mlp.experts.3.bias, backbone.blocks.0.mlp.experts.4.weight, backbone.blocks.0.mlp.experts.4.bias, backbone.blocks.0.mlp.experts.5.weight, backbone.blocks.0.mlp.experts.5.bias, backbone.blocks.1.mlp.experts.0.weight, backbone.blocks.1.mlp.experts.0.bias, backbone.blocks.1.mlp.experts.1.weight, backbone.blocks.1.mlp.experts.1.bias, backbone.blocks.1.mlp.experts.2.weight, backbone.blocks.1.mlp.experts.2.bias, backbone.blocks.1.mlp.experts.3.weight, backbone.blocks.1.mlp.experts.3.bias, backbone.blocks.1.mlp.experts.4.weight, backbone.blocks.1.mlp.experts.4.bias, backbone.blocks.1.mlp.experts.5.weight, backbone.blocks.1.mlp.experts.5.bias, backbone.blocks.2.mlp.experts.0.weight, backbone.blocks.2.mlp.experts.0.bias, backbone.blocks.2.mlp.experts.1.weight, backbone.blocks.2.mlp.experts.1.bias, backbone.blocks.2.mlp.experts.2.weight, backbone.blocks.2.mlp.experts.2.bias, backbone.blocks.2.mlp.experts.3.weight, backbone.blocks.2.mlp.experts.3.bias, backbone.blocks.2.mlp.experts.4.weight, backbone.blocks.2.mlp.experts.4.bias, backbone.blocks.2.mlp.experts.5.weight, backbone.blocks.2.mlp.experts.5.bias, backbone.blocks.3.mlp.experts.0.weight, backbone.blocks.3.mlp.experts.0.bias, backbone.blocks.3.mlp.experts.1.weight, backbone.blocks.3.mlp.experts.1.bias, backbone.blocks.3.mlp.experts.2.weight, backbone.blocks.3.mlp.experts.2.bias, backbone.blocks.3.mlp.experts.3.weight, backbone.blocks.3.mlp.experts.3.bias, backbone.blocks.3.mlp.experts.4.weight, backbone.blocks.3.mlp.experts.4.bias, backbone.blocks.3.mlp.experts.5.weight, backbone.blocks.3.mlp.experts.5.bias, backbone.blocks.4.mlp.experts.0.weight, backbone.blocks.4.mlp.experts.0.bias, backbone.blocks.4.mlp.experts.1.weight, backbone.blocks.4.mlp.experts.1.bias, backbone.blocks.4.mlp.experts.2.weight, backbone.blocks.4.mlp.experts.2.bias, backbone.blocks.4.mlp.experts.3.weight, backbone.blocks.4.mlp.experts.3.bias, backbone.blocks.4.mlp.experts.4.weight, backbone.blocks.4.mlp.experts.4.bias, backbone.blocks.4.mlp.experts.5.weight, backbone.blocks.4.mlp.experts.5.bias, backbone.blocks.5.mlp.experts.0.weight, backbone.blocks.5.mlp.experts.0.bias, backbone.blocks.5.mlp.experts.1.weight, backbone.blocks.5.mlp.experts.1.bias, backbone.blocks.5.mlp.experts.2.weight, backbone.blocks.5.mlp.experts.2.bias, backbone.blocks.5.mlp.experts.3.weight, backbone.blocks.5.mlp.experts.3.bias, backbone.blocks.5.mlp.experts.4.weight, backbone.blocks.5.mlp.experts.4.bias, backbone.blocks.5.mlp.experts.5.weight, backbone.blocks.5.mlp.experts.5.bias, backbone.blocks.6.mlp.experts.0.weight, backbone.blocks.6.mlp.experts.0.bias, backbone.blocks.6.mlp.experts.1.weight, backbone.blocks.6.mlp.experts.1.bias, backbone.blocks.6.mlp.experts.2.weight, backbone.blocks.6.mlp.experts.2.bias, backbone.blocks.6.mlp.experts.3.weight, backbone.blocks.6.mlp.experts.3.bias, backbone.blocks.6.mlp.experts.4.weight, backbone.blocks.6.mlp.experts.4.bias, backbone.blocks.6.mlp.experts.5.weight, backbone.blocks.6.mlp.experts.5.bias, backbone.blocks.7.mlp.experts.0.weight, backbone.blocks.7.mlp.experts.0.bias, backbone.blocks.7.mlp.experts.1.weight, backbone.blocks.7.mlp.experts.1.bias, backbone.blocks.7.mlp.experts.2.weight, backbone.blocks.7.mlp.experts.2.bias, backbone.blocks.7.mlp.experts.3.weight, backbone.blocks.7.mlp.experts.3.bias, backbone.blocks.7.mlp.experts.4.weight, backbone.blocks.7.mlp.experts.4.bias, backbone.blocks.7.mlp.experts.5.weight, backbone.blocks.7.mlp.experts.5.bias, backbone.blocks.8.mlp.experts.0.weight, backbone.blocks.8.mlp.experts.0.bias, backbone.blocks.8.mlp.experts.1.weight, backbone.blocks.8.mlp.experts.1.bias, backbone.blocks.8.mlp.experts.2.weight, backbone.blocks.8.mlp.experts.2.bias, backbone.blocks.8.mlp.experts.3.weight, backbone.blocks.8.mlp.experts.3.bias, backbone.blocks.8.mlp.experts.4.weight, backbone.blocks.8.mlp.experts.4.bias, backbone.blocks.8.mlp.experts.5.weight, backbone.blocks.8.mlp.experts.5.bias, backbone.blocks.9.mlp.experts.0.weight, backbone.blocks.9.mlp.experts.0.bias, backbone.blocks.9.mlp.experts.1.weight, backbone.blocks.9.mlp.experts.1.bias, backbone.blocks.9.mlp.experts.2.weight, backbone.blocks.9.mlp.experts.2.bias, backbone.blocks.9.mlp.experts.3.weight, backbone.blocks.9.mlp.experts.3.bias, backbone.blocks.9.mlp.experts.4.weight, backbone.blocks.9.mlp.experts.4.bias, backbone.blocks.9.mlp.experts.5.weight, backbone.blocks.9.mlp.experts.5.bias, backbone.blocks.10.mlp.experts.0.weight, backbone.blocks.10.mlp.experts.0.bias, backbone.blocks.10.mlp.experts.1.weight, backbone.blocks.10.mlp.experts.1.bias, backbone.blocks.10.mlp.experts.2.weight, backbone.blocks.10.mlp.experts.2.bias, backbone.blocks.10.mlp.experts.3.weight, backbone.blocks.10.mlp.experts.3.bias, backbone.blocks.10.mlp.experts.4.weight, backbone.blocks.10.mlp.experts.4.bias, backbone.blocks.10.mlp.experts.5.weight, backbone.blocks.10.mlp.experts.5.bias, backbone.blocks.11.mlp.experts.0.weight, backbone.blocks.11.mlp.experts.0.bias, backbone.blocks.11.mlp.experts.1.weight, backbone.blocks.11.mlp.experts.1.bias, backbone.blocks.11.mlp.experts.2.weight, backbone.blocks.11.mlp.experts.2.bias, backbone.blocks.11.mlp.experts.3.weight, backbone.blocks.11.mlp.experts.3.bias, backbone.blocks.11.mlp.experts.4.weight, backbone.blocks.11.mlp.experts.4.bias, backbone.blocks.11.mlp.experts.5.weight, backbone.blocks.11.mlp.experts.5.bias

**Comment by Polaris7777777** [comment]
@syguan96 Sorry to bother you,have you addressed the problems, I am faced with the same problem as well.
