### ISSUE TITLE
how to fine tuning of coco pose estimation

### ISSUE THREAD

**Issue by hotelbread** [ViTAE-Transformer/ViTPose#68]
Hi, thank you for your advice before.

actually I want to fine tuning of your pose-estimation model(coco). It means that not only just for training of pre-trained model(MAE) but also I want to train the check-point .pth. 
For example, about Vit_small_coco, I have pre-trained model(small_pretrained.pth, I think it hasnt weight value about coco) and check point file(vitpose_small.pth). So I used the vitpose_small.pth when I inference sth. And when I trained the model, I used small_pretrained.pth. I need train/update vitpose_small.pth.
How can I do? I tried to put the PATH about vitpose_small.pth to configs file 
(model = dict(pretrained = None) -> model = dict(pretrained = PATH)
Unfortunately, it looks not working.
How can I do?

seotae89@gmail.com

**Comment by Annbless** [comment]
Please use the load_from options instead. It will load pre-trained weights into the backbone and the keypoint heads.

**Comment by eliabntt** [comment]
Hi @Annbless, what if I want to change the head while keeping the main weights?
