### ISSUE TITLE
a minor question about the simple head

### ISSUE THREAD

**Issue by ydhongHIT** [ViTAE-Transformer/ViTPose#72]
In your words and figure, the sequence is bilinear, relu, and conv while in the formula and codes, the sequence is relu, bilinear, and conv. Does this tiny change matter? And what is the motivation behind adding an extra relu?

**Comment by Annbless** [comment]
Thanks for your questions. The influence of the tiny change is rather minor. The motivation to use an extra ReLU is simple. Without ReLU, the simple head is a linear projection layer only and can be absorbed into the linear layer in the final FFN, which may affect the pre-trained weights too much during training.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.
