### ISSUE TITLE
which one of the checkpoints output layer size is 133?

### ISSUE THREAD

**Issue by hosseinfeiz** [ViTAE-Transformer/ViTPose#76]
Hi Thanks for your work and releasing the pretrained models. I tried inferencing a video with vitpose+_huge.pth checkpoint but the output is 17 keypoints. Can you help finding the checkpoint with 133 output layer

**Comment by Annbless** [comment]
Please split the checkpoints and use the checkpoint corresponds to the wholebody dataset.

**Comment by hosseinfeiz** [comment]
Thanks
