### ISSUE TITLE
Reproduce the video results in README

### ISSUE THREAD

**Issue by ykk648** [ViTAE-Transformer/ViTPose#9]
Which config and weight file have you used?

**Comment by ykk648** [comment]
aic config path error, three of them are `base` model config

**Comment by Annbless** [comment]
Thanks for your pointing out! We have corrected the config path in the Readme file.

The video results are generated using the models used for MS COCO datasets. A larger model will always give better performance. The base model can provide good results on the videos and the performance of the huge model will be better.

**Comment by ykk648** [comment]
thx, issue close
